### ISSUE TITLE
Preprocessor query parameter must be optional.

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/focusing-manager#3]
The patientId should be optional for the case of sending the IPS, as patient is not retrieved by focusing manager.

**Comment by aalonsolopez** [comment]
Hi @jkiddo! This issue is now closed. The request don`t require always the patientID, but in OpenAPI.yaml it was mandatory in all the requests. It's not deployed on FOSPS at this moment, and if you revise the commit and it's all OK, then I make a new release with your yesterday's commit and a deploy on FOSPS cluster.

**Comment by jkiddo** [comment]
LGTM

**Comment by jkiddo** [comment]
@aalonsolopez I was a bit quick there - see https://github.com/Gravitate-Health/focusing-manager/pull/7 . I don't understand why you prefer to have the patientId as path parameter. IMHO, I think it should be a query param if needed at all.

**Comment by aalonsolopez** [comment]
> @aalonsolopez I was a bit quick there - see https://github.com/Gravitate-Health/focusing-manager/pull/7 . I don't understand why you prefer to have the patientId as path parameter. IMHO, I think it should be a query param if needed at all.

In fact, I don't know why we still have that PatientID parameter, because I think it's unused. I will make the last check tomorrow (I promise it's the last in that task, sorry for the inconvenience), and if this parameter is unused, I can delete it. If it's used in another endpoint in the Swagger, I will fix it as soon as possible tomorrow.

Thank you for everything @jkiddo

**Comment by jkiddo** [comment]
@10alejospain - I'm gonna reopen this until @aalonsolopez has fixed the openapi spec.

**Comment by aalonsolopez** [comment]
We think that this commit solves all the problems. We also deleted some endpoints that was on the document despite they were not related with Focusing Manager.  If you see all clear, pls close this issue.

**Comment by jkiddo** [comment]
I'm unable to test whether it works as the service fails when posting an IPS - see https://github.com/Gravitate-Health/focusing-manager/issues/8

**Comment by aalonsolopez** [comment]
Did you add the preprocessing query parameter as I said in #8?

**Comment by jkiddo** [comment]
And initially - this is what should be required (and nothing else - at least for my flow)
1) Patient Id OR Patient Identifier OR Patient IPS bundle.
2) ePI Identifier

**All other stuff should be optional**

**Comment by 10alejospain** [comment]
We'll modify the behaviour of the API so everything is optional except the IPS and the ePI related stuff. By default we'll apply the most advanced preproccesor avaible. (RN the manual one)

**Comment by jkiddo** [comment]
@10alejospain by when will that be the case?

**Comment by aalonsolopez** [comment]
We have an Issue only for the lenses case, that is my priority RN. I assume that the preprocessing optionality is also important, so I can do it next.

**Comment by amedranogil** [comment]
The default behaviour for all focusing APIs is that if Processors are not provided, all available will be selected. The same goes for lenses.

**Comment by aalonsolopez** [comment]
>

Noted!

**Comment by jkiddo** [comment]
@aalonsolopez let me know when its done and make a PR to https://github.com/hl7-eu/gravitate-health/blob/master/Gravitate.postman_collection.json with an updated example

**Comment by aalonsolopez** [comment]
I will change the Issue name to make it more clear and accurate to the real issue here

**Comment by aalonsolopez** [comment]
@jkiddo this issue is done. I will close this issue, merge it to main, make a new release (v1.2.0) with this change and the #4 and make a pull request to the repo that you told me about with the updated endpoints (that are the same). If there's some problem that need a fix, reopen this issue or create a new one.
